//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEARCH_OPTIONS
    {
        public int SEARCH_OPTIONS_ID { get; set; }
        public string OPTIONS { get; set; }
    }
}
