//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYMPTOM_RESLUTS
    {
        public int SYMPTOM_RESLUTS_ID { get; set; }
        public int SYMPTOMS_ID { get; set; }
        public string SYMPTOMS_DESC { get; set; }
    }
}
