//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farming.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_FARM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHILD_FARM()
        {
            this.SEARCH_OPTIONS = new HashSet<SEARCH_OPTIONS>();
        }
    
        public int CHILD_FARM_ID { get; set; }
        public Nullable<int> MASTER_FARM_ID { get; set; }
        public string CHILD_FARM_NAME { get; set; }
    
        public virtual MASTER_FARM MASTER_FARM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEARCH_OPTIONS> SEARCH_OPTIONS { get; set; }
    }
}
