//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farming.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_FARM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_FARM()
        {
            this.CHILD_FARM = new HashSet<CHILD_FARM>();
        }
    
        public int MASTER_FARM_ID { get; set; }
        public string MASTER_FARM_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHILD_FARM> CHILD_FARM { get; set; }
    }
}
