//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farming.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEARCH_OPTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEARCH_OPTIONS()
        {
            this.SYMPTOMS = new HashSet<SYMPTOM>();
        }
    
        public int SEARCH_OPTIONS_ID { get; set; }
        public Nullable<int> CHILD_FARM_ID { get; set; }
        public string OPTIONS { get; set; }
    
        public virtual CHILD_FARM CHILD_FARM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYMPTOM> SYMPTOMS { get; set; }
    }
}
