//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farming.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYMPTOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYMPTOM()
        {
            this.SYMPTOM_RESULTS = new HashSet<SYMPTOM_RESULTS>();
        }
    
        public int SYMPTOMS_ID { get; set; }
        public Nullable<int> CHILD_FARM_ID { get; set; }
        public Nullable<int> SEARCH_OPTIONS_ID { get; set; }
        public string SYMPTOMS_DESC { get; set; }
        public byte[] SYMPTOMS_IMAGE { get; set; }
    
        public virtual SEARCH_OPTIONS SEARCH_OPTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYMPTOM_RESULTS> SYMPTOM_RESULTS { get; set; }
    }
}
