//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_FARM
    {
        public int CHILD_FARM_ID { get; set; }
        public Nullable<int> MASTER_FARM_ID { get; set; }
        public string CHILD_FARM_NAME { get; set; }
    }
}
